### ISSUE TITLE
npm install 报错 

### ISSUE THREAD

**Issue by bjcangyue** [Array-Huang/webpack-seed#1]
packge.json里的import-loader、imports-loader 无法正常Install 。

**Comment by Array-Huang** [comment]
哦，这样吗？难道npm上这俩包被撤掉了？不过我印象中都没用到这俩loader了，我看看要不要删掉

**Comment by Array-Huang** [comment]
搞清楚了，我用的是淘宝的源，是有import-loader的，而官方的源这个包应该是被撤下来了。
事实上，这项目也没有用import-loader了，我就删掉好了。

谢谢反映问题。
