### ISSUE TITLE
webpack-dev-server的自动刷新

### ISSUE THREAD

**Issue by ToPeas** [Array-Huang/webpack-seed#10]
一直对这个自动刷新很疑惑，以前用gulp。用的browser-sync的刷新，现在想用这种热替换。。。
但是我发现修改了less文件，页面也没有变化，在packjson里面start添加了--hot也没有效果呀

**Comment by Array-Huang** [comment]
抱歉我对这方面没有研究，可能需要什么plugin才能监听文件目录

**Comment by ieoh** [comment]
我在linux和mac都尝试了 是可以监听文件变化的 但是windows下不行


发自 网易邮箱大师
在2016年11月03日 23:09，小落Martox 写道:

一直对这个自动刷新很疑惑，以前用gulp。用的browser-sync的刷新，现在想用这种热替换。。。
但是我发现修改了less文件，页面也没有变化，在packjson里面start添加了--hot也没有效果呀

**Comment by Array-Huang** [comment]
@ieoh 哦？是跟操作系统有关系？那可能是权限问题？

我之前用的一个less编译工具，叫做koala的，是可以监控less文件变化然后自动编译成css的

**Comment by ieoh** [comment]
我猜小落的问题可能是:不能监听文件变化然后自动打包吧 是不是不只针对less文件 我还没找到原因 只是在不同系统下尝试了一下
发自 网易邮箱大师
在2016年11月04日 09:39，Array Huang 写道:

@ieoh 哦？是跟操作系统有关系？那可能是权限问题？

我之前用的一个less编译工具，叫做koala的，是可以监控less文件变化然后自动编译成css的

**Comment by Array-Huang** [comment]
我其实也并不是完全没有尝试过，只是试了好多方案都没什么反应。我自己用的也是windows系统。

嘿嘿，如果你们用的是我这套脚手架（或类似的方案）而又试验自动刷新成果的话，麻烦告诉我一声，谢谢了哈。

**Comment by ieoh** [comment]
我在linux和mac下用的感觉非常棒，非常感谢您的这套脚手架，加深了我对webpack的理解。非常厉害！
等遇到问题会向您请教




在 2016-11-04 09:49:12，"Array Huang" <notifications@github.com> 写道：


我其实也并不是完全没有尝试过，只是试了好多方案都没什么反应。我自己用的也是windows系统。

嘿嘿，如果你们用的是我这套脚手架（或类似的方案）而又试验自动刷新成果的话，麻烦告诉我一声，谢谢了哈。

**Comment by Array-Huang** [comment]
@ieoh 好的，非常欢迎

**Comment by cqgsm** [comment]
能开个群么，让我们菜鸟讨论下

**Comment by Array-Huang** [comment]
@cqgsm 哈哈哈哈，开群感觉都不会有多少人加进来，还是别了吧，有问题可以开issue或者放到segmentfault嘛。

**Comment by Array-Huang** [comment]
@Nutlee 大兄弟似乎解决了这个问题了，有时间我也学习学习，哈哈哈~~

也推荐大家来看看哈

[《关于前端工程化的思考及《webpack多页应用架构系列》mock开发环境改造》](http://nutlee.space/2016/10/24/%E5%85%B3%E4%BA%8E%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%8C%96%E7%9A%84%E6%80%9D%E8%80%83%E5%8F%8A%E3%80%8Awebpack%E5%A4%9A%E9%A1%B5%E5%BA%94%E7%94%A8%E6%9E%B6%E6%9E%84%E7%B3%BB%E5%88%97%E3%80%8Bmock%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%94%B9%E9%80%A0/)
[Nutlee/webpack-seed](https://github.com/Nutlee/webpack-seed)
