### ISSUE TITLE
关于 运行src 中 public-resource和pages 中 cannot resolve moudule 'css' ！

### ISSUE THREAD

**Issue by LouisKim07** [Array-Huang/webpack-seed#14]
大哥，您是不是 遗漏了 css 文件未上传了？？ 您的这套 体系非常值得学习，在线等！ 急！

**Comment by Array-Huang** [comment]
你贴完整的错误提示上来吧，这个看着像是没有配置css-loader

**Comment by LouisKim07** [comment]
厉害了我的大哥！可 为什么我执行npm install 会出现 css-loader 未加载到呢？？？

**Comment by Array-Huang** [comment]
噢？是没有成功安装css-loader么？那安装的时候应该会有报错提示你原因的，那你现在安装成功了么？

**Comment by LouisKim07** [comment]
安装时 并未出错，运行测试时就出 错误了！不过现在解决了，谢谢大哥的指导！
