### ISSUE TITLE
模板问题

### ISSUE THREAD

**Issue by weizhijie** [Array-Huang/webpack-seed#16]
模板文件我是file-loader 到 build目录里面,供后期ajax拉取模板和数据在浏览器渲染, 模板用到图片也是file-loader 到build 里面, 模板图片地址怎么设置? 有没有好的方法

**Comment by Array-Huang** [comment]
像我这样把所有file-loader搬运的资源的路径全部集中到一个[config](https://github.com/Array-Huang/webpack-seed/blob/master/src/public-resource/config/build-file.config.js)里，然后你渲染的时候就提出来用呗
