### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by Kuohao-wu** [Array-Huang/webpack-seed#17]
![image](https://cloud.githubusercontent.com/assets/16506726/22617389/f136f90c-eafe-11e6-803e-65e6c6a22b23.png)

![image](https://cloud.githubusercontent.com/assets/16506726/22617394/07563dd8-eaff-11e6-89b4-ca6ee89f9c8c.png)

我在node_modules里面的webpack里确实找不到这个emitter文件，在下webpack新手一枚，请指教

**Comment by Array-Huang** [comment]
嗯？我在node_modules里也没找到这个`webpack/hot/emitter`，但是也没有报错。你全局的webpack是1还是2的？

**Comment by Array-Huang** [comment]
嗯，搞明白了，我这个脚手架需要用webpack和webpack-dev-server的v1版本，但是现在webpack-dev-server默认安装的都是v2版本了，所以就出问题了。
这个问题我刚刚已经改好并上传了：[v1.4.2](https://github.com/Array-Huang/webpack-seed/tree/v1.4.2)
至于你现在的情况，需要先卸载掉v2版本的webpack-dev-server，再安装回v1版本的webpack-dev-server：

```
npm uninstall -g webpack-dev-server
npm i -g webpack-dev-server@^1.16.2
npm uninstall webpack-dev-server
npm i webpack-dev-server@^1.16.2
```
