### ISSUE TITLE
webpack 多入口文件的新增删除如何watch

### ISSUE THREAD

**Issue by cylzh** [Array-Huang/webpack-seed#18]
rt

**Comment by Array-Huang** [comment]
没办法watch的，因为这相当于改了webpack的配置，改了webpack的配置就需要重新调用webpack

**Comment by cylzh** [comment]
谢谢！我现在是用gulp+webpack构建项目的。然后gulp.watch的时候，每次重新生成新的entry，然后重新去跑webpack
