### ISSUE TITLE
棒棒哒，做成 generator 发布吧

### ISSUE THREAD

**Issue by fuchao2012** [Array-Huang/webpack-seed#2]

**Comment by Array-Huang** [comment]
谢谢夸奖，不过我不是很明白你说的generator是什么？异步编程的新玩意儿？

**Comment by fuchao2012** [comment]
yeoman.io

**Comment by fuchao2012** [comment]
用了一下，大致的感受比较复杂。上手难度比较大呢。如果能将配置汇总，抽离出变化的部分就更好了。
另外，现在配置 bower+webpack, gulp+webpack的比较少，当然官方不推荐这么用，但是我们的工具链升级还是想着向前兼容一些。

**Comment by Array-Huang** [comment]
嗯，不知道你是从哪里知道我这个项目的呢？我这个项目主要是搭配系列文章作为示例来使用的，我的文章每一篇都是一个小专题，都只讲一小块内容，就会比较好理解，而要是光看这个项目本身，虽然不包含任何的业务逻辑，但是就架构本身而言，跟我公司的项目是一样的，复杂度肯定是有的，不然我饭都没得吃了（笑

《webpack多页应用架构系列》放在我个人的技术博客上了：https://segmentfault.com/blog/array_huang

**Comment by Array-Huang** [comment]
然后，我没用用过bower和gulp呢，webpack之前我是用requireJS的，现在webpack能满足我所有对工具、架构的要求，估计也就不会去碰其它的构建工具了吧

**Comment by fuchao2012** [comment]
我就是在这篇里看到的。
工具链啥的肯定是适合自己团队的才是最好的。希望你们用的爽（：

**Comment by Array-Huang** [comment]
嗯，segmentfault上面我记得是有gulp+webpack的文章，还挺火的，你可以搜搜看
