### ISSUE TITLE
如果你是像我一样利用HtmlWebpackPlugin来生成HTML并自动加载chunk的话，请务必在<head>里手写<script>来加载Dll文件。

### ISSUE THREAD

**Issue by yangchongduo** [Array-Huang/webpack-seed#20]
你说的这个头部 怎么加 我就是加不上去

**Comment by Array-Huang** [comment]
在这里加：https://github.com/Array-Huang/webpack-seed/blob/master/src/public-resource/components/header/html.ejs

**Comment by yangchongduo** [comment]
你的ejs 我的html 这个怎么弄

**Comment by yangchongduo** [comment]
<script src="/dll/vendor.js"></script>  我直接这么写 总是pending 这个js就是加载不了 求助

**Comment by Array-Huang** [comment]
因为你的dll文件路径不对呀。

你要找个地方，每次启动webpack打包的时候，用file-loader把dll文件搬到合适的位置。

路径！路径！路径很重要！
