### ISSUE TITLE
ie8

### ISSUE THREAD

**Issue by YealZoy** [Array-Huang/webpack-seed#23]
有没有试过兼容ie8?
我已经疯了

**Comment by Array-Huang** [comment]
对了，`npm start`是加上了热加载的`webpack-dev-server`，需要用到websocket的，所以肯定是不支持IE8的，但是实际上你`npm run build`出来的文件是兼容IE8的

**Comment by YealZoy** [comment]
静态页面require的样式和图片都是对的，自己写的js代码`alert`都没弹框，而且`ie8`下`Object.defineProperty`这个有问题，曾经引过babel-ployfill core-js es5-shim es5-sham都失败了 
![ ](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1490176675&di=3394607777e3a0f04fd57a4dccb985b5&imgtype=jpg&er=1&src=http%3A%2F%2Fwww.7scs.com%2Fdown%2FUploadPic%2F2016-4%2F201641623521891604.jpg)

**Comment by Array-Huang** [comment]
啥？你说的是我这个脚手架本身？还是说你在这个脚手架上面加的自己的东西？

**Comment by YealZoy** [comment]
自己加的东西，

**Comment by Array-Huang** [comment]
额，那这不是我这脚手架的问题了吧，你发去SF吧
