### ISSUE TITLE
dll引用问题

### ISSUE THREAD

**Issue by ultra-ran** [Array-Huang/webpack-seed#25]
使用的你的最新代码测试使用dll打包时遇到问题，请求支援
我对源文件做了如下修改：
1. 将build-file.config.js的注释去掉
2. 将plugins.config.js中关于dll的注释去掉
3. 将footer/html.ejs中引用jquery的语句去掉
4. 在header/html.ejs中加入dll文件的引用
5. 运行npm run dll ，npm run build，npm run start
浏览器控制台报错时浏览器抛出错误Uncaught TypeError: $ is not a function，找不到jeuery，从浏览器控制台中可以看到，在html加载后dll文件开始加载。
![qq20170327-0 2x](https://cloud.githubusercontent.com/assets/12745859/24333832/eda81982-1291-11e7-9c50-2cfe3e50808f.png)

**Comment by Array-Huang** [comment]
之前升级webpack2的时候，搞不清楚在webpack2里expose-loader是怎么用的，所以就把jquery提出来直接用`<script>`来加载，再辅以[externals](https://github.com/Array-Huang/webpack-seed/blob/master/webpack-config/externals.config.js)了。
所以如果你把jquery打包进dll文件里，必须把`externals`给关掉，然后把`expose-loader`开起来

**Comment by ultra-ran** [comment]
我试了你的方法，dll文件报错，“Uncaught ReferenceError: jQuery is not defined”

![Uploading 微信截图_20170327152149.png…]()，去掉externals.config.js文件中对jquery的配置
![Uploading   @@429.png…]()，在common.page.js中引用jquery

我猜测是dll中包含jquery和bootstrap.min.js文件，bootstrap.min.js依赖jqerry所以报错

**Comment by Array-Huang** [comment]
除了开expose-loader，我还建议把provide-plugin开起来

**Comment by Array-Huang** [comment]
就像我文章里写的一样

**Comment by ultra-ran** [comment]
不折腾了，这些都开开估计jquery又打包进bundle中了

**Comment by Array-Huang** [comment]
不会的，只要你在dll文件里打包了jquery，无论怎么折腾都不会进主bundle里。不过我倒是觉得放`<script>`里直接加载也挺不错的
