### ISSUE TITLE
devServer.config.js配置问题

### ISSUE THREAD

**Issue by ultra-ran** [Array-Huang/webpack-seed#26]
1. vender/devServer.config.js这个devServer.config.js中module.export应该是module.exports
2. 开启热更新后plugins.dev.config.js中是不是应该增加new webpack.HotModuleReplacementPlugin()，否则报错

**Comment by Array-Huang** [comment]
1. 嗯？我哪里有`devServer.config.js`？
2. 我印象中是有`--inline --hot`的话就会自动加这个`HotModuleReplacementPlugin`的

**Comment by ultra-ran** [comment]
1. 你看一下这个目录webpack-seed/webpack-config/vendor/devServer.config.js
2. 似乎并不会自动加，浏览器报错了，加上后ok

**Comment by Array-Huang** [comment]
1. 还真的是，不知怎么的我这边竟然是ok的
2. 我这边也没有报错
