### ISSUE TITLE
现在已经不用 npm-scripts 下面的东西了吗

### ISSUE THREAD

**Issue by fenghou1st** [Array-Huang/webpack-seed#29]
package.json 里没有运行  npm-scripts 下面的代码了，其他地方也没发现。
是因为 webpack2 自动会清空 build 目录，不用自己写代码了吗？

**Comment by Edwinhei** [comment]
我也很想知道为啥

**Comment by Array-Huang** [comment]
已重新启用清理build目录的脚本了，请看master分支或v2.0.1的tag
