### ISSUE TITLE
npm run build 

### ISSUE THREAD

**Issue by xvinc** [Array-Huang/webpack-seed#3]
修改模板和less，文件看到好像有热更新，但在页面就是没显示出来，那这样每次修改都要重新build ,然后在启动服务起了看效果？

**Comment by Array-Huang** [comment]
抱歉没做hot-reload，一般我都是用`npm run watch`（也就是`webpack --watch`），改完源码就自己刷新浏览器，这样的话是不需要重新build的，跟hot-reload的差别就是要手动刷新浏览器而已
