### ISSUE TITLE
请问 css-loader 的 options: -autoprefixer 的作用是什么？

### ISSUE THREAD

**Issue by fenghou1st** [Array-Huang/webpack-seed#30]
我 google 了好久，不论是 css-loader，还是 postcss、autoprefixer 的设置项里都没提到相关设置，只好麻烦您亲自讲解了。

代码如下：
https://github.com/Array-Huang/webpack-seed/blob/master/webpack-config/module.product.config.js#L15

**Comment by Array-Huang** [comment]
`-autoprefixer`的意思是不需要autoprefixer来参与minimize的过程，怕就怕它把一些兼容老旧浏览器的css代码段给干掉了
