### ISSUE TITLE
静态资源 JS CDN

### ISSUE THREAD

**Issue by givebest** [Array-Huang/webpack-seed#34]
项目介绍里讲：
* 编译后的程序不依赖于外部的资源（包括css、font、图片等资源都做了迁移），可以整体放到CDN上。 

但： `npm run build` 后，我看 JS 还是和入口 HTML 在一个目录，没有分离。

**Comment by Array-Huang** [comment]
你的理解错了，“不依赖于外部的资源”的意思就是把html和其它静态资源放一起，这实际上才是web前端最好的形态
