### ISSUE TITLE
点击切换页面时，页面布局混乱，闪一下后css样式才有效果

### ISSUE THREAD

**Issue by blitheinsz** [Array-Huang/webpack-seed#35]
点击切换页面时，页面布局混乱，闪一下后css样式才有效果？是不是css被延迟加载了

**Comment by Array-Huang** [comment]
开发环境是把css打包到js里，加载完js才把css插入html，所以会有闪烁；生产环境是直接把css输出成文件，那就跟传统的页面是一样的，就不会有闪烁了
