### ISSUE TITLE
webpack3.0

### ISSUE THREAD

**Issue by songdun** [Array-Huang/webpack-seed#38]
webpack3.0出来了，要不要一步升级到位啊？

**Comment by Array-Huang** [comment]
据说是无痛升级，你可以考虑上。不过我暂时就不上了，webpack3新特性我暂时还没有特别想要的。

**Comment by songdun** [comment]
我一直用的版本1，放到项目上很6啊，升级到2很困难啊，你能整理下你升级的点吗？

**Comment by Array-Huang** [comment]
首先来说，自己的源码不需要怎么改，改的就是webpack的配置，其实主要也就是一些格式语法的变动

**Comment by Array-Huang** [comment]
至于改动的话，你可以参考参考[这里](https://github.com/Array-Huang/webpack-seed/commit/500c060e6fa33bd92beb9bd6d6c59c4ff900d2f9)
