### ISSUE TITLE
打包后显示不完整

### ISSUE THREAD

**Issue by s641135196** [Array-Huang/webpack-seed#39]
使用npm run build后运行新生成的build文件下的index.html报下面错。如果是使用npm strat运行在浏览器中正常。是什么问题了
![image](https://user-images.githubusercontent.com/8079013/28727339-16345e3a-73f7-11e7-9e92-d657b1a6d294.png)

**Comment by Array-Huang** [comment]
打包后的文件需要放服务器上，或者改改路径什么的也行，改成相对路径
