### ISSUE TITLE
新手小白求助基础问题，如何引入其它js文件。。。

### ISSUE THREAD

**Issue by unssnu** [Array-Huang/webpack-seed#41]
您好，我有一个navbar的jquery插件，我将它的html写入了top-nav\html.ejs，样式显示正常
但我在html代码之后，继续引入<script>插件的js文件</script>，并且继续用$声明一个变量，这些都报错了

请问这个js文件正确的存放路径是哪里？还是ejs引入js文件的写法我写错了。。。

GET http://localhost:8080/index/index/top-nav/jquery.bootstrap-autohidingnavbar.min.js 
page.html:130 Uncaught ReferenceError: $ is not defined
    at page.html:130

以上是控制台报的错，麻烦您帮忙指导一下，十分感谢~~~~~~

**Comment by Array-Huang** [comment]
报错的原因是因为你在加载jquery之前加载了这个jq插件。

正确的加载时机要看你是怎么加载jquery的，你就在jq之后加载jq插件就OK了。

可以参考我这篇文章：[《webpack多页应用架构系列（四）：老式jQuery插件还不能丢，怎么兼容？》](https://segmentfault.com/a/1190000006887523)
