### ISSUE TITLE
npm i 报错

### ISSUE THREAD

**Issue by iq9891** [Array-Huang/webpack-seed#42]
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file

**Comment by Array-Huang** [comment]
啥？报错就只有这么一点点吗？看不出有什么毛病

**Comment by webdaniu** [comment]
要么被墙了 用cnpm i 
要么没有权限 用sudo cnpm i
要么 我也不知道怎么弄了

**Comment by Array-Huang** [comment]
哦，我用的虽然是npm，但改了源为淘宝的节点，所以应该跟cnpm是一样的
