### ISSUE TITLE
如何保存session呢

### ISSUE THREAD

**Issue by chounvwudi** [Array-Huang/webpack-seed#43]
你好，请问这个框架如何保存后端session？

**Comment by Array-Huang** [comment]
session这一块其实与本webpack脚手架关系不大，不过你一定要问的话：
1. 传统的方式就是后端在 http header 里配置好，把`session_id`自动存 cookie 里呗。
2. 稍微现代一点的方式，就是前端访问某个 API 获取到 `session_id` 了，就存进 localStorage 里，然后每次请求 API 的时候都带上这个`session_id` 。

**Comment by chounvwudi** [comment]
谢谢您的回复，另外有个问题貌似文件[devServer.config.js](https://github.com/Array-Huang/webpack-seed/blob/master/webpack-config/vendor/devServer.config.js)不起作用，修改端口号无效

**Comment by Array-Huang** [comment]
嗯，看了一下的确是改端口号没用

**Comment by Array-Huang** [comment]
已经改好了，原来是webpack2把这devServer参数提到第一级来了：https://doc.webpack-china.org/configuration/dev-server
