### ISSUE TITLE
require('!!file-loader?name=index.html!../../index.html');

### ISSUE THREAD

**Issue by webdaniu** [Array-Huang/webpack-seed#44]
require('!!file-loader?name=index.html!../../index.html'); 中的这个脚本代表含义是如果有file-loader加载器就把name=index.html，给个教程地址我学习下去加深下理解，!!不是代表true么，搞不懂。。黄老师原来是你，久仰久仰

**Comment by Array-Huang** [comment]
啊，我还有黄老师这个称号么？

`file-loader`的文档在[这里](https://doc.webpack-china.org/loaders/file-loader/)，至于前面的这`!!`，由于年代有点久远，彼时还是webpack1的时代，具体出处我已经不记得了，大意是本次`require`忽略webpack的loader（包括`preloader`）全局配置。
