### ISSUE TITLE
页面会先显示没有样式然后才加载样式显示

### ISSUE THREAD

**Issue by Ignorantforce** [Array-Huang/webpack-seed#46]
问题描述：页面会先显示没有样式然后才加载样式显示
![image](https://user-images.githubusercontent.com/22272002/30726512-d77ec150-9f7d-11e7-95cf-7261cb5937dd.png)

**Comment by well-monkey** [comment]
我也发现了这个问题了。这个怎么解决呢

**Comment by iamllitog** [comment]
开发环境才这样，仔细看文章 https://segmentfault.com/a/1190000006897458

**Comment by Array-Huang** [comment]
开发环境会把css都打包到js里，所以要等js加载好了才有样式，因此会出现这种情况；但是在生产环境下，css会生成css文件，并插入到`<style />`里，因此就不会出现这种情况了。
