### ISSUE TITLE
手动指定文件入口还是强制了

### ISSUE THREAD

**Issue by xvinc** [Array-Huang/webpack-seed#5]
module.exports=[
  'index/login',
  'index/index',
  -  'alert/index',
  -  'user/edit-password', 'user/modify-info',
];
翻看你的更新修改，貌似不行，还是强制到登入后的页面了

**Comment by Array-Huang** [comment]
额，你是不是弄错“文件入口”的意思了？文件入口指的是webpack配置中的entry参数。

你想一开始跳到登录页是吧？改[`webpack-seed/index.html`](https://github.com/Array-Huang/webpack-seed/blob/master/index.html)就好了

**Comment by xvinc** [comment]
原来强制写在里面了，我看很多写的都在里面，有点模糊，我以为指代上面文件入口文件了，不然其他种写法是怎样的？能否指点下，看很多实例感觉还是模糊

**Comment by xvinc** [comment]
单页面好像都指向那个build.js就自动访问了

**Comment by Array-Huang** [comment]
我这个不是单页的，是多页的呀，跟你不用webpack是一样的。那个webpack-seed/index.html只是相当于一个重定向的作用

**Comment by xvinc** [comment]
那除了这种写法还有其他中写法没

**Comment by Array-Huang** [comment]
你是想问重定向么？前端就只能靠这种方式来实现了

**Comment by xvinc** [comment]
我看其他demo的多页面外面那个生成的index.html直接废弃在那，想看看能不能结合vue-cli webpack来搞搞

**Comment by Array-Huang** [comment]
这个就是这么用的，不需要有其它的内容，只是单纯的跳转而已

**Comment by xvinc** [comment]
那好的
