### ISSUE TITLE
请问是否考虑升级到webpack3和最新版的vue呢？我想用您的脚手架搭建项目。

### ISSUE THREAD

**Issue by easyfast** [Array-Huang/webpack-seed#50]
请问是否考虑升级到webpack3和最新版的vue呢？我想用您的脚手架搭建项目。但是webpack3的配置似乎和您在文章中说的不完全一样。

**Comment by Array-Huang** [comment]
我的文章里的代码是webpack1时代的，不过配置其实还是那些配置，只是配置的格式有较大的改动；而这个`webpack-seed`里的代码是webpack2，webpack2的配置跟webpack3的差不太远，你可以参考一下；至于是否升级，短期内暂时不折腾了，我公司的项目都一直用着webpack2的
