### ISSUE TITLE
如何在ejs中引入图片

### ISSUE THREAD

**Issue by feibenren** [Array-Huang/webpack-seed#55]
按照你的思路，自己写了一个demo，但是，问题来了，如何在ejs模板中引入img，我再网上查，看到可以通过`<img src="<%=require('images/index/banner1.png')%>" >`这种方式来引用，好高兴，但是，打包的时候，却无法打包。。。。。。

**Comment by Array-Huang** [comment]
这种方法是正确的，你可能是路径出了问题；注意如果用相对路径的话，其实是以你的这个ejs文件作为标准的
