### ISSUE TITLE
components如何包含js/css/image等？

### ISSUE THREAD

**Issue by hgt803** [Array-Huang/webpack-seed#56]
能否在 top-nav 这模块写成demo？谢谢

**Comment by hgt803** [comment]
在： https://www.jianshu.com/p/dfc9a21740d0找到答案

所以干脆还是交由base.less一并加载了算了。

我设计了一个common.page.js，并在每一个页面的入口文件里都首先加载这common.page.js，那么，只要我在这common.page.js里加载base.less，所有的页面都能享受到这份基础CSS代码段。

**Comment by Array-Huang** [comment]
事实上，如果可以的话，还是遵循组件化的原则，给每个组件设置一个`main.js`，并且在这个js文件里加载css和html
