### ISSUE TITLE
如果去掉 Bootstrap3及SB-Admin需要修改那些文件

### ISSUE THREAD

**Issue by EagleWolf** [Array-Huang/webpack-seed#58]
整合Bootstrap3及主题SB-Admin，但其实换掉也很简单，或者干脆不用CSS框架也行。

如果去掉 Bootstrap3及SB-Admin需要修改那些文件

**Comment by Array-Huang** [comment]
我在`src/public-resource/logic/common.page.js`里引用了bootstrap的js文件；另外也引用了一个全局的样式`base.less`，在这个less文件里我引用了bootstrap的css文件以及主题SB-Admin的样式（被我拆散成多个less文件分别存放了），你可以考虑直接抛弃重写这个less文件
