### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by waittingbar** [Array-Huang/webpack-seed#6]
$ npm run build

> webpack-seed@1.2.2 build E:\webpack-seed
> node npm-scripts/before-build.script.js && webpack --progress --colors --bail

module.js:471
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\webpack-seed\npm-scripts\before-build.script.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-seed@1.2.2 build: `node npm-scripts/before-build.script.js && webpack --progress --colors --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-seed@1.2.2 build script 'node npm-scripts/before-build.script.js && webpack --progress --colors --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-scripts/before-build.script.js && webpack --progress --colors --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\webpack-seed\npm-debug.log

**Comment by Array-Huang** [comment]
嗯？这个报错是说找不到模块rimraf，装一下就好了，我已经列进`package.json`里面的了
``` javascript
npm install
```
