### ISSUE TITLE
需要全局安装 webpack-dev-server 吧

### ISSUE THREAD

**Issue by Nutlee** [Array-Huang/webpack-seed#7]
您好

1.  使用说明第三步， 需要全局安装 webpack-dev-server 吧，不然这条命令都没法执行。一开始看到 package.json 本地依赖有了 webpack-dev-serve 还以为不用全局装。

2. 如果本地安装 webpack-dev-server 同时又要监控编译监控刷新，需要在 package.json 的 start 里加上 --hot ，并且 output.config.js 中的 publicPath 改成 'http://localhost:8080/build/' ，不改 publicPath 没反应的。这样看起来没问题，但是如果有错误，比如 ESlint 的错误，后台没任何反应，前端控制台会报加载资源错误，应该是编译出错了。所以还是放弃了.........

3. 有个疑问，对于这个项目来说，按道理我只 build ，然后本地打开，即 file:/// 这样打开应该也没问题的吧，事实上.... 如果这样打开引用资源会报错，资源路径多了一个 "../" 层级，这个不知道算不算正常。在webpack-dev-server 下正常显示正常的。

谢谢❤

**Comment by Nutlee** [comment]
更正
2. Node中不显示错误是因为 package.json 的 start 的值写了不必要的参数... --quiet 。

**Comment by Array-Huang** [comment]
1. 在项目本地安装webpack/webpack-dev-server的确都不好使，我把package.json里的干掉吧。
2. 噢，我不知道--quiet会把错误提示也干掉，那我还是去掉吧。
3. 嗯，路径的确是有问题，我已经重新整理过了
